[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483647

# add the custom stuff to the editor palette whenever the editor is opened
[[patches]]
[patches.pattern]
target = "states/Editor.lua"
pattern = "self.eventPalette = palette"
position = "before"
payload = '''
for _, path in ipairs(bbp.loader.events) do
	palette = self:paletteFromFolder(palette, path)
end
'''
match_indent = true
times = 1
