[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483647

[[patches]]
[patches.module]
source = "bbp/init.lua"
before = "conf.lua"
name = "bbp"

[[patches]]
[patches.module]
source = "bbp/utils.lua"
before = "conf.lua"
name = "bbp.utils"

[[patches]]
[patches.module]
source = "bbp/loader.lua"
before = "conf.lua"
name = "bbp.loader"

[[patches]]
[patches.module]
source = "bbp/gui.lua"
before = "conf.lua"
name = "bbp.gui"

[[patches]]
[patches.pattern]
target = "conf.lua"
pattern = "function love.conf(*)"
position = "before"
payload = '''
lovely = require("lovely")
bbp = require("bbp")
bbp.loader.loadMods()
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "preload/sprites.lua"
pattern = "return sprites"
position = "before"
payload = "bbp.loader.loadSprites(sprites)"
match_indent = true

[[patches]]
[patches.pattern]
target = "preload/sounds.lua"
pattern = "return sounds"
position = "before"
payload = "bbp.loader.loadSounds(sounds)"
match_indent = true

[[patches]]
[patches.pattern]
target = "preload/shaders.lua"
pattern = "return shaders"
position = "before"
payload = "bbp.loader.loadShaders(shaders)"
match_indent = true

[[patches]]
[patches.pattern]
target = "preload/animations.lua"
pattern = "return animations"
position = "before"
payload = "bbp.loader.loadAnimations(animations)"
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "loc.load(\"data/localization.json\")"
position = "after"
payload = "bbp.loader.loadLocales()"
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "dofile('preload/entities.lua')"
position = "after"
payload = "bbp.loader.loadEntities()"
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "dofile('preload/states.lua')"
position = "after"
payload = "bbp.loader.loadStates()"
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "findFiles('levelformat/events')"
position = "after"
payload = "bbp.loader.loadEvents()"
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "cs = bs.load(project.initState)"
position = "before"
payload = '''
bbp.loader.loadIcons()
bbp.loader.runMains()
'''
match_indent = true
