[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483647

# during the first load of conf.lua bbp doesnt exist
# so the first path is taken, where we define bbp
# and then unload and require conf.lua again
# but since this time bbp exists,
# it will execute the original code instead

[[patches]]
[patches.pattern]
target = "conf.lua"
pattern = "function love.conf(*)"
position = "before"
payload = '''
if not bbp then
    lovely = require("lovely")
    bbp = require("bbp")
    bbp.loader.loadMods()

    print("reloading conf.lua to apply patches done to it by mods")
    package.loaded["conf"] = nil
    return require("conf")
else
'''
match_indent = true

[[patches]]
[patches.regex]
target = "conf.lua"
pattern = "^end"
position = "after"
payload = "end"
verbose = true
times = 1

[[patches]]
[patches.pattern]
target = "preload/sprites.lua"
pattern = "return sprites"
position = "before"
payload = "bbp.loader.loadSprites(sprites)"
match_indent = true

[[patches]]
[patches.pattern]
target = "preload/sounds.lua"
pattern = "return sounds"
position = "before"
payload = "bbp.loader.loadSounds(sounds)"
match_indent = true

[[patches]]
[patches.pattern]
target = "preload/shaders.lua"
pattern = "return shaders"
position = "before"
payload = "bbp.loader.loadShaders(shaders)"
match_indent = true

[[patches]]
[patches.pattern]
target = "preload/animations.lua"
pattern = "return animations"
position = "before"
payload = "bbp.loader.loadAnimations(animations)"
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "loc.load(\"data/localization.json\")"
position = "after"
payload = "bbp.loader.loadLocales()"
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "dofile('preload/entities.lua')"
position = "after"
payload = "bbp.loader.loadEntities()"
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "dofile('preload/states.lua')"
position = "after"
payload = "bbp.loader.loadStates()"
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = "findFiles('levelformat/events')"
position = "after"
payload = "bbp.loader.loadEvents()"
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "cs = bs.load(project.initState)"
position = "before"
payload = '''
bbp.loader.loadIcons()
bbp.loader.runMains()
'''
match_indent = true
