[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483647

[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = "self.mainMenu:addOption('credits',function()"
position = "before"
payload = '''
self.mainMenu:addOption('Mods', function()
	cs = bs.load('Mods')
	self.menuMusicManager:clearOnBeatHooks()
	cs.menuMusicManager = self.menuMusicManager
	cs:init()
end, 17 * 3, nil, sprites.menu.mods)

for i = 1, 4 do
	self.mainMenu.options.main[i].y = self.mainMenu.options.main[i].y - 17
end
'''
match_indent = true
